/*
    Actions Types
*/

const LOGON_USER = 'LOGON_USER';
const LOADER = 'LOADING';
const GET_LIST_GENERAL_STATE = 'GET_LIST_GENERAL_STATE';
const LOGOUT = 'LOGOUT';
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
const UPDATE_STATE_ROUTE = 'UPDATE_STATE_ROUTE';
const UPDATE_ROUTE_DELETED = 'UPDATE_ROUTE_DELETED';
const GET_LIST_ROUTE = 'GET_LIST_ROUTE';
const LOADING_UPDATE_DELETED = 'LOADING_UPDATE_DELETED';
const DATA_GENERATION = 'DATA_GENERATION';
const LIST_ROUTE_GENERATE = 'LIST_ROUTE_GENERATE';
const LOADER_TABLE = 'LOADER_TABLE'
const LOADER_TABLE_DELETED = 'LOADER_TABLE_DELETED'
const LOADER_TABLE_STATE = 'LOADER_TABLE_STATE'
const GENERATE_MASTER_DATA = 'GENERATE_MASTER_DATA'
const UPLOAD_REP = 'UPLOAD_REP'

export{
    LOGON_USER,
    LOADER,
    GET_LIST_GENERAL_STATE,
    LOGOUT,
    OPEN_MODAL,
    CLOSE_MODAL
    ,UPDATE_STATE_ROUTE
    ,UPDATE_ROUTE_DELETED
    ,GET_LIST_ROUTE
    ,LOADING_UPDATE_DELETED
    ,DATA_GENERATION
    ,LIST_ROUTE_GENERATE
    ,LOADER_TABLE
    ,LOADER_TABLE_DELETED
    ,LOADER_TABLE_STATE
    ,GENERATE_MASTER_DATA
    ,UPLOAD_REP
}