//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebAsesores.com.plumrose.cgsapdb1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="binding", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Z_WEB_GET_XSALES_ASESOR_01OperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_WEB_LIST_ASESORES_01OperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_WEB_GET_DATOS_ASESOR_01OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service() {
            this.Url = global::WebAsesores.Properties.Settings.Default.WebAsesores_com_plumrose_cgsapdb1_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Z_WEB_GET_XSALES_ASESOR_01CompletedEventHandler Z_WEB_GET_XSALES_ASESOR_01Completed;
        
        /// <remarks/>
        public event Z_WEB_LIST_ASESORES_01CompletedEventHandler Z_WEB_LIST_ASESORES_01Completed;
        
        /// <remarks/>
        public event Z_WEB_GET_DATOS_ASESOR_01CompletedEventHandler Z_WEB_GET_DATOS_ASESOR_01Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZSD_SITE_SERVICIOS:Z_WEB_GET_XSALES_ASESOR" +
            "_01Request", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Z_WEB_GET_XSALES_ASESOR_01Response", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public Z_WEB_GET_XSALES_ASESOR_01Response Z_WEB_GET_XSALES_ASESOR_01([System.Xml.Serialization.XmlElementAttribute("Z_WEB_GET_XSALES_ASESOR_01", Namespace="urn:sap-com:document:sap:rfc:functions")] Z_WEB_GET_XSALES_ASESOR_01 Z_WEB_GET_XSALES_ASESOR_011) {
            object[] results = this.Invoke("Z_WEB_GET_XSALES_ASESOR_01", new object[] {
                        Z_WEB_GET_XSALES_ASESOR_011});
            return ((Z_WEB_GET_XSALES_ASESOR_01Response)(results[0]));
        }
        
        /// <remarks/>
        public void Z_WEB_GET_XSALES_ASESOR_01Async(Z_WEB_GET_XSALES_ASESOR_01 Z_WEB_GET_XSALES_ASESOR_011) {
            this.Z_WEB_GET_XSALES_ASESOR_01Async(Z_WEB_GET_XSALES_ASESOR_011, null);
        }
        
        /// <remarks/>
        public void Z_WEB_GET_XSALES_ASESOR_01Async(Z_WEB_GET_XSALES_ASESOR_01 Z_WEB_GET_XSALES_ASESOR_011, object userState) {
            if ((this.Z_WEB_GET_XSALES_ASESOR_01OperationCompleted == null)) {
                this.Z_WEB_GET_XSALES_ASESOR_01OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_WEB_GET_XSALES_ASESOR_01OperationCompleted);
            }
            this.InvokeAsync("Z_WEB_GET_XSALES_ASESOR_01", new object[] {
                        Z_WEB_GET_XSALES_ASESOR_011}, this.Z_WEB_GET_XSALES_ASESOR_01OperationCompleted, userState);
        }
        
        private void OnZ_WEB_GET_XSALES_ASESOR_01OperationCompleted(object arg) {
            if ((this.Z_WEB_GET_XSALES_ASESOR_01Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_WEB_GET_XSALES_ASESOR_01Completed(this, new Z_WEB_GET_XSALES_ASESOR_01CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZSD_SITE_SERVICIOS:Z_WEB_LIST_ASESORES_01R" +
            "equest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Z_WEB_LIST_ASESORES_01Response", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public Z_WEB_LIST_ASESORES_01Response Z_WEB_LIST_ASESORES_01([System.Xml.Serialization.XmlElementAttribute("Z_WEB_LIST_ASESORES_01", Namespace="urn:sap-com:document:sap:rfc:functions")] Z_WEB_LIST_ASESORES_01 Z_WEB_LIST_ASESORES_011) {
            object[] results = this.Invoke("Z_WEB_LIST_ASESORES_01", new object[] {
                        Z_WEB_LIST_ASESORES_011});
            return ((Z_WEB_LIST_ASESORES_01Response)(results[0]));
        }
        
        /// <remarks/>
        public void Z_WEB_LIST_ASESORES_01Async(Z_WEB_LIST_ASESORES_01 Z_WEB_LIST_ASESORES_011) {
            this.Z_WEB_LIST_ASESORES_01Async(Z_WEB_LIST_ASESORES_011, null);
        }
        
        /// <remarks/>
        public void Z_WEB_LIST_ASESORES_01Async(Z_WEB_LIST_ASESORES_01 Z_WEB_LIST_ASESORES_011, object userState) {
            if ((this.Z_WEB_LIST_ASESORES_01OperationCompleted == null)) {
                this.Z_WEB_LIST_ASESORES_01OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_WEB_LIST_ASESORES_01OperationCompleted);
            }
            this.InvokeAsync("Z_WEB_LIST_ASESORES_01", new object[] {
                        Z_WEB_LIST_ASESORES_011}, this.Z_WEB_LIST_ASESORES_01OperationCompleted, userState);
        }
        
        private void OnZ_WEB_LIST_ASESORES_01OperationCompleted(object arg) {
            if ((this.Z_WEB_LIST_ASESORES_01Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_WEB_LIST_ASESORES_01Completed(this, new Z_WEB_LIST_ASESORES_01CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZSD_SITE_SERVICIOS:Z_WEB_GET_DATOS_ASESOR_" +
            "01Request", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Z_WEB_GET_DATOS_ASESOR_01Response", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public Z_WEB_GET_DATOS_ASESOR_01Response Z_WEB_GET_DATOS_ASESOR_01([System.Xml.Serialization.XmlElementAttribute("Z_WEB_GET_DATOS_ASESOR_01", Namespace="urn:sap-com:document:sap:rfc:functions")] Z_WEB_GET_DATOS_ASESOR_01 Z_WEB_GET_DATOS_ASESOR_011) {
            object[] results = this.Invoke("Z_WEB_GET_DATOS_ASESOR_01", new object[] {
                        Z_WEB_GET_DATOS_ASESOR_011});
            return ((Z_WEB_GET_DATOS_ASESOR_01Response)(results[0]));
        }
        
        /// <remarks/>
        public void Z_WEB_GET_DATOS_ASESOR_01Async(Z_WEB_GET_DATOS_ASESOR_01 Z_WEB_GET_DATOS_ASESOR_011) {
            this.Z_WEB_GET_DATOS_ASESOR_01Async(Z_WEB_GET_DATOS_ASESOR_011, null);
        }
        
        /// <remarks/>
        public void Z_WEB_GET_DATOS_ASESOR_01Async(Z_WEB_GET_DATOS_ASESOR_01 Z_WEB_GET_DATOS_ASESOR_011, object userState) {
            if ((this.Z_WEB_GET_DATOS_ASESOR_01OperationCompleted == null)) {
                this.Z_WEB_GET_DATOS_ASESOR_01OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_WEB_GET_DATOS_ASESOR_01OperationCompleted);
            }
            this.InvokeAsync("Z_WEB_GET_DATOS_ASESOR_01", new object[] {
                        Z_WEB_GET_DATOS_ASESOR_011}, this.Z_WEB_GET_DATOS_ASESOR_01OperationCompleted, userState);
        }
        
        private void OnZ_WEB_GET_DATOS_ASESOR_01OperationCompleted(object arg) {
            if ((this.Z_WEB_GET_DATOS_ASESOR_01Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_WEB_GET_DATOS_ASESOR_01Completed(this, new Z_WEB_GET_DATOS_ASESOR_01CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_WEB_GET_XSALES_ASESOR_01 {
        
        private string i_OPCIONField;
        
        private string i_USER_WEBField;
        
        private DATUM_RANGE[] rDATEField;
        
        private RANGE_C10[] rPERNRField;
        
        private RANGE_C10[] rVKBURField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_OPCION {
            get {
                return this.i_OPCIONField;
            }
            set {
                this.i_OPCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_USER_WEB {
            get {
                return this.i_USER_WEBField;
            }
            set {
                this.i_USER_WEBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DATUM_RANGE[] RDATE {
            get {
                return this.rDATEField;
            }
            set {
                this.rDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RANGE_C10[] RPERNR {
            get {
                return this.rPERNRField;
            }
            set {
                this.rPERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RANGE_C10[] RVKBUR {
            get {
                return this.rVKBURField;
            }
            set {
                this.rVKBURField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class DATUM_RANGE {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDSITE_ESLIST_ASESOR01 {
        
        private string pERNRField;
        
        private string sNAMEField;
        
        private string vKBUR_TField;
        
        private string cODIGOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SNAME {
            get {
                return this.sNAMEField;
            }
            set {
                this.sNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VKBUR_T {
            get {
                return this.vKBUR_TField;
            }
            set {
                this.vKBUR_TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class CCHRS_PERSK_RANGE {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class CCHRS_PERSG_RANGE {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RANGE_C10 {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_WEB_GET_XSALES_ASESOR_01Response {
        
        private string e_SALIDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_SALIDA {
            get {
                return this.e_SALIDAField;
            }
            set {
                this.e_SALIDAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_WEB_LIST_ASESORES_01 {
        
        private string i_USER_WEBField;
        
        private CCHRS_PERSG_RANGE[] rPERSGField;
        
        private CCHRS_PERSK_RANGE[] rPERSKField;
        
        private RANGE_C10[] rVKBURField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_USER_WEB {
            get {
                return this.i_USER_WEBField;
            }
            set {
                this.i_USER_WEBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CCHRS_PERSG_RANGE[] RPERSG {
            get {
                return this.rPERSGField;
            }
            set {
                this.rPERSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CCHRS_PERSK_RANGE[] RPERSK {
            get {
                return this.rPERSKField;
            }
            set {
                this.rPERSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RANGE_C10[] RVKBUR {
            get {
                return this.rVKBURField;
            }
            set {
                this.rVKBURField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_WEB_LIST_ASESORES_01Response {
        
        private ZSDSITE_ESLIST_ASESOR01[] t_LISTDATOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSDSITE_ESLIST_ASESOR01[] T_LISTDATOS {
            get {
                return this.t_LISTDATOSField;
            }
            set {
                this.t_LISTDATOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_WEB_GET_DATOS_ASESOR_01 {
        
        private string i_PERNRField;
        
        private string i_USER_WEBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_PERNR {
            get {
                return this.i_PERNRField;
            }
            set {
                this.i_PERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_USER_WEB {
            get {
                return this.i_USER_WEBField;
            }
            set {
                this.i_USER_WEBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_WEB_GET_DATOS_ASESOR_01Response {
        
        private string e_EMAILField;
        
        private string e_NAMEField;
        
        private string e_VKBURField;
        
        private string e_VKGRPField;
        
        private string e_VKORGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_EMAIL {
            get {
                return this.e_EMAILField;
            }
            set {
                this.e_EMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_NAME {
            get {
                return this.e_NAMEField;
            }
            set {
                this.e_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_VKBUR {
            get {
                return this.e_VKBURField;
            }
            set {
                this.e_VKBURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_VKGRP {
            get {
                return this.e_VKGRPField;
            }
            set {
                this.e_VKGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_VKORG {
            get {
                return this.e_VKORGField;
            }
            set {
                this.e_VKORGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Z_WEB_GET_XSALES_ASESOR_01CompletedEventHandler(object sender, Z_WEB_GET_XSALES_ASESOR_01CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_WEB_GET_XSALES_ASESOR_01CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_WEB_GET_XSALES_ASESOR_01CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Z_WEB_GET_XSALES_ASESOR_01Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Z_WEB_GET_XSALES_ASESOR_01Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Z_WEB_LIST_ASESORES_01CompletedEventHandler(object sender, Z_WEB_LIST_ASESORES_01CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_WEB_LIST_ASESORES_01CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_WEB_LIST_ASESORES_01CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Z_WEB_LIST_ASESORES_01Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Z_WEB_LIST_ASESORES_01Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Z_WEB_GET_DATOS_ASESOR_01CompletedEventHandler(object sender, Z_WEB_GET_DATOS_ASESOR_01CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_WEB_GET_DATOS_ASESOR_01CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_WEB_GET_DATOS_ASESOR_01CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Z_WEB_GET_DATOS_ASESOR_01Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Z_WEB_GET_DATOS_ASESOR_01Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591