//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAsesores.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FDV_Entities : DbContext
    {
        public FDV_Entities()
            : base("name=FDV_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<general> general { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<route> route { get; set; }
        public virtual DbSet<journeyTrace> journeyTrace { get; set; }
    
        public virtual int XSR_ITF_GeneralDownload(string rotCode, string jrnCode, Nullable<bool> job)
        {
            var rotCodeParameter = rotCode != null ?
                new ObjectParameter("rotCode", rotCode) :
                new ObjectParameter("rotCode", typeof(string));
    
            var jrnCodeParameter = jrnCode != null ?
                new ObjectParameter("jrnCode", jrnCode) :
                new ObjectParameter("jrnCode", typeof(string));
    
            var jobParameter = job.HasValue ?
                new ObjectParameter("job", job) :
                new ObjectParameter("job", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XSR_ITF_GeneralDownload", rotCodeParameter, jrnCodeParameter, jobParameter);
        }
    
        public virtual int XSR_ITF_ClearRoute(string rotCode, string jrnCode, Nullable<bool> job, string journeyUpdate)
        {
            var rotCodeParameter = rotCode != null ?
                new ObjectParameter("rotCode", rotCode) :
                new ObjectParameter("rotCode", typeof(string));
    
            var jrnCodeParameter = jrnCode != null ?
                new ObjectParameter("jrnCode", jrnCode) :
                new ObjectParameter("jrnCode", typeof(string));
    
            var jobParameter = job.HasValue ?
                new ObjectParameter("job", job) :
                new ObjectParameter("job", typeof(bool));
    
            var journeyUpdateParameter = journeyUpdate != null ?
                new ObjectParameter("JourneyUpdate", journeyUpdate) :
                new ObjectParameter("JourneyUpdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XSR_ITF_ClearRoute", rotCodeParameter, jrnCodeParameter, jobParameter, journeyUpdateParameter);
        }
    
        public virtual int XSR_ITF_GeneralUpload()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XSR_ITF_GeneralUpload");
        }
    
        public virtual int XSR_ITF_MasterData(Nullable<bool> job)
        {
            var jobParameter = job.HasValue ?
                new ObjectParameter("job", job) :
                new ObjectParameter("job", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XSR_ITF_MasterData", jobParameter);
        }
    }
}
