//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAsesores.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class general
    {
        public string rotCode { get; set; }
        public System.DateTime gnlDate { get; set; }
        public short gnlMonthWorkingDays { get; set; }
        public short gnlDaysUpToDate { get; set; }
        public System.DateTime gnlNextWorkingDay { get; set; }
        public Nullable<decimal> gnlExchangeRate { get; set; }
        public string gnlDummy1 { get; set; }
        public string gnlDummy2 { get; set; }
        public string gnlDummy3 { get; set; }
        public string jrnCode { get; set; }
        public Nullable<byte> gnlStatus { get; set; }
        public Nullable<System.DateTime> gnlStatusDate { get; set; }
        public Nullable<byte> gnlPartialStatus { get; set; }
        public Nullable<System.DateTime> gnlPartialStatusDate { get; set; }
    
        public virtual route route { get; set; }
    }
}
