//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAsesores.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class journeyTrace
    {
        public long jrtCode { get; set; }
        public string rotCode { get; set; }
        public string jrnCode { get; set; }
        public Nullable<byte> jrtStatus { get; set; }
        public Nullable<System.DateTime> jrtStatusDate { get; set; }
        public Nullable<byte> jrtPartialStatus { get; set; }
        public Nullable<System.DateTime> jrtPartialStatusDate { get; set; }
        public string jrtDummy { get; set; }
    
        public virtual route route { get; set; }
    }
}
