//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAsesores.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public route()
        {
            this.general = new HashSet<general>();
            this.journeyTrace = new HashSet<journeyTrace>();
        }
    
        public string rotCode { get; set; }
        public string rotName { get; set; }
        public string lgnCode { get; set; }
        public string prcCodeForSale { get; set; }
        public string prcCodeForReturn { get; set; }
        public string prcCodeForSettlement { get; set; }
        public string txnCode { get; set; }
        public string tckCode { get; set; }
        public string tryCode { get; set; }
        public string chaCode { get; set; }
        public string groCode { get; set; }
        public string ttpCode { get; set; }
        public bool rotCheckSameOrderClass { get; set; }
        public Nullable<decimal> rotMaxPercentageSpecial { get; set; }
        public Nullable<decimal> rotAccumulatedSalesOfTheMonth { get; set; }
        public Nullable<decimal> rotAccumulatedOfSpecial { get; set; }
        public string rotMessage1 { get; set; }
        public string rotMessage2 { get; set; }
        public string rotMessage3 { get; set; }
        public string rotDummy1 { get; set; }
        public string rotDummy2 { get; set; }
        public string rotInvoiceHeader1 { get; set; }
        public string rotInvoiceHeader2 { get; set; }
        public string rotInvoiceHeader3 { get; set; }
        public string rotInvoiceHeader4 { get; set; }
        public string rotInvoiceHeader5 { get; set; }
        public string rotInvoiceBottom1 { get; set; }
        public string rotInvoiceBottom2 { get; set; }
        public string rotInvoiceBottom3 { get; set; }
        public string rotInvoiceBottom4 { get; set; }
        public string rotInvoiceBottom5 { get; set; }
        public bool rotInactive { get; set; }
        public Nullable<short> rotAverageTime { get; set; }
        public Nullable<short> rotAverageSpeed { get; set; }
        public string rotTimerValidationCode { get; set; }
        public string rotHtmlPath { get; set; }
        public bool C_deleted { get; set; }
        public int C_stamp { get; set; }
        public string gr2Code { get; set; }
        public string rotDriverCode { get; set; }
        public string rotCoDriverCode { get; set; }
        public string rotTractorNumber { get; set; }
        public string rotTrailerNumber { get; set; }
        public Nullable<long> C_rowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<general> general { get; set; }
        public virtual login login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<journeyTrace> journeyTrace { get; set; }
    }
}
